#!/bin/bash

sxhkd &

# Polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V    

bspc config border_width         3 # era 2
bspc config window_gap           5 # era 12

bspc config split_ratio          5.0 # era 0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Cores das Bordas
bspc config normal_border_color   \#161616 #Janela inativa
bspc config active_border_color   \#CCCCCC #?
bspc config focused_border_color  \#000000 #Janela ativa
bspc config presel_feedback_color \#FFFFFF #?

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a epiphany-browser desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Papel de Parede
feh --bg-scale $HOME/Imagens/wallpapers/img_00.jpg

# Configuração de Teclado
setxkbmap -model abnt2 -layout br -variant abnt2

# Iniciados com o sistema
dunst &
compton &
pulseaudio --start &
network-manager &
xfce4-power-manager &
